[package]
name = "wrtt-lib"
version = "0.1.0"
authors = ["PrettyWood <em.jolibois@gmail.com>"]
license = "MIT"
repository = "https://github.com/PrettyWood/wasm-rust-ts-template"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "./src/lib/lib.rs"

[dependencies]
wasm-bindgen = "0.2"
